### ISSUE TITLE
[São Paulo/SP] PHP Developer na Resource IT

### ISSUE THREAD

**Issue by Nati-Ferracini** [phpdevbr/vagas#314]
## Descrição da vaga

Para profissional Sênior considerar mínimo 5 anos de atuação.

- Terá que realizar análise e desenolvimento de portais e sistemas em php, seguindo as melhores práticas , utilizando controle de versão integrada com todo o time.
Formação:
- Formação de nível superior, graduação ou pós-graduação, em tecnologia da informação ou áreas correlatas;
Qualificações:
- Desenvolvimento com lumen laravel
- Desenvolvimento AngularJS;
- Desenvolvimento PL/SQL e NoSQL Database
- Experiência em OO com PHP;
- Conhecimento em avaliação de código-fonte;
- Conhecimento em ferramentas (Jira, Docker)
- Vivência com ambiente linux e docker e experiência com testes; 
- Bom relacionamento interpessoal e facilidade para trabalhar em equipes; 

## Local

Escritório, São Paulo/SP - Paulista 

## Benefícios

- Plano de saúde
- Seguro de vida
- VR de R$ 440/dia
- Auxílio creche
- Plano Odontológico 

## Requisitos

**Obrigatórios:**
- 4 anos de experiência com PHP 

## Contratação

CLT a combinar

## Nossa empresa

Somos uma tech partner, focada em entrega de transformação digital.
Somos uma multinacional brasileira com 27 anos no mercado e estamos entre as maiores integradoras de TI do Brasil.
Temos mais de 21 escritórios em 5 países, 27 anos de experiência, mais de 20 parceiros comerciais, 3000 colaboradores e mais de 300 clientes...e estamos só começando!!!

## Como se candidatar

Por favor envie um email para natalia.oliveira@resourceit.com com seu CV anexado - enviar no assunto: Vaga PHP

### Experiência
- Pleno
- Sênior

**Comment by moreiraandre** [comment]
Acho que esse e-mail está com problema

**Comment by CasonWebDev** [comment]
Não está com problema, é quando vc clica no e-mail o link está adicionando a palavra "para" antes ou seja quando clica no link: o e-mail fica paranatalia..... E não natalia... TB tive esse pormenor HeheheEm 28 de jan de 2019 13:36, André Moreira <notifications@github.com> escreveu:Acho que esse e-mail está com problema



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phpdevbr/vagas","title":"phpdevbr/vagas","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/phpdevbr/vagas"}},"updates":{"snippets":[{"icon":"PERSON","message":"@moreiraandre in #314: Acho que esse e-mail está com problema"}],"action":{"name":"View Issue","url":"https://github.com/phpdevbr/vagas/issues/314#issuecomment-458178612"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/phpdevbr/vagas/issues/314#issuecomment-458178612",

"url": "https://github.com/phpdevbr/vagas/issues/314#issuecomment-458178612",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by moreiraandre** [comment]
@CasonWebDev Vdd kkkk, valeu mano

**Comment by ravanscafi** [comment]
favor repostar a vaga caso a mesma ainda esteja em aberto :wink:
