### ISSUE TITLE
[Campo Bom/RS] PHP Developer na Deliver IT

### ISSUE THREAD

**Issue by SejaDeliver** [phpdevbr/vagas#492]
## Descrição da vaga

Estamos em busca de um (a) Dev PHP para atuar em conjunto com um time ágil, em um sistema transacional responsável por todas as unidades nacionais e internacionais da empresa, do segmento da indústria.

## Local

Campo Bom - RS

## Benefícios

- Plano de saúde;
- Plano odontológico;
- Vale refeição ou alimentação;
- Vale transporte;
- Premiação por tempo de empresa;
- Premiação por indicação.

#### Diferenciais

O ambiente de trabalho é super dinâmico, com flexibilidade de horários e conta com um time super parceiro e sinérgico \o/

## Requisitos

**Obrigatórios:**

- PHP 5+
- ExtJS
- JavaScript

**Diferenciais:**
- Curtir um ambiente com muita troca de conhecimento e utilização de metodologias ágeis \o/ 

## Contratação

CLT

## Nossa empresa

A Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.

Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.

Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.

Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.

## Como se candidatar

Acesse https://deliverit.gupy.io/jobs/92794 para maiores informações e se candidatar s2

### Alocação:
- Presencial

### Contratação:
- CLT

### Experiência
- Pleno

**Comment by Devitibeck** [comment]
Boa tarde. Vocês aceitam pessoas de fora?De: SejaDeliverEnviado:sexta-feira, 8 de novembro de 2019 17:33Para: phpdevbr/vagasCc:SubscribedAssunto: [phpdevbr/vagas] [CampoBom/RS] PHP Developer na Deliver IT (#492) Descrição da vagaEstamos em busca de um (a) Dev PHP para atuar em conjunto com um time ágil, em um sistema transacional responsável por todas as unidades nacionais e internacionais da empresa, do segmento da indústria.LocalCampo Bom - RSBenefíciosPlano de saúde;Plano odontológico;Vale refeição ou alimentação;Vale transporte;Premiação por tempo de empresa;Premiação por indicação.DiferenciaisO ambiente de trabalho é super dinâmico, com flexibilidade de horários e conta com um time super parceiro e sinérgico \o/RequisitosObrigatórios:PHP 5+ExtJSJavaScriptDiferenciais:Curtir um ambiente com muita troca de conhecimento e utilização de metodologias ágeis \o/ContrataçãoCLTNossa empresaA Deliver IT é uma consultoria de serviços de tecnologia da informação. Nossa missão é entregar valor aos nossos clientes, através de serviços de tecnologia de informação, dentro de uma relação de parceira.Acreditamos em equipes multidisciplinares, que possuem confiança em suas relações e sobretudo transparência. Nosso time se caracteriza pelo engajamento, comprometimento e foco na qualidade das entregas.Acreditamos que a qualidade dos nossos processos se deve a todas as pessoas que fazem parte da Deliver, e por isso prezamos por um ambiente de trabalho agradável, leve e muito amigável. Aqui os colaboradores têm espaço para o seu desenvolvimento profissional, oportunidade de trabalhar em projetos globais e para empresas de reconhecimento a nível nacional.Nosso portfólio de serviço utiliza tecnologias vanguardistas dentre as seguintes linhas: Fábrica de Software, Business Intelligence, Mobile e Outsourcing.Como se candidatarAcesse https://deliverit.gupy.io/jobs/92794 para maiores informações e se candidatar s2LabelsAlocação:PresencialContratação:CLTExperiênciaPleno—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
